# don't change the following 8 lines
baseURL = "http://tec.myfortinet.com/"
canonifyURLs = false
relativeURLs = true
languageCode = "en-US"
defaultContentLanguage = "en"
theme = ["hugo-theme-relearn"]
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false
uglyurls = true
enableEmoji = true


################################ BEGIN EDITING ################################
# Display Title of the project
title = "Capture the Flag with FortiEDR and FortiAnalyzer"

[params]
# Author of the site, will be used in meta information
author.name = "Jason Palm, Kyle Krisher, Jason Graun"

# Select a color theme.
# special
# themeVariant = "Xperts2024"
#themeVariant = "Xperts2023"
# red
themeVariant = "Xperts2025"
# purple
# themeVariant = "Spotlight"
# green
# themeVariant = "Demo"
# blue
#themeVariant = "UseCase"

# The banner text under Fortinet logo on the top left of the project. Better to be short.
logoBannerText = "CTF with FEDR & FAZ"
# Small text under the title
logoBannerSubText = "Fortinet Partners"
################################# END EDITING #################################


# Shows a checkmark for visited pages on the menu
showVisitedLinks = true
# Disable search function. It will hide search bar
disableSearch = false
# Javascript and CSS cache are automatically busted when new version of site is generated.
# Set this to true to disable this behavior (some proxies don't handle well this optimization)
disableAssetsBusting = true
# Set this to true to disable copy-to-clipboard button for inline code.
disableInlineCopyToClipBoard = false
# A title for shortcuts in menu is set by default. Set this to true to disable it.
disableShortcutsTitle = false

# If set to false, a Home button will appear below the search bar on the menu.
# It is redirecting to the landing page of the current language if specified. (Default is "/")
disableLandingPageButton = true
# When using mulitlingual website, disable the switch language button.
disableLanguageSwitchingButton = true
# Hide breadcrumbs in the header and only show the current page title
disableBreadcrumb = false
# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = false
# Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"


landingPageName = "<i class='fas fa-home'></i> Home"

version = "v0.0.0"

[[menu.shortcuts]]
name = "<i class='fas fa-print'></i> Single Page View (for printing)"
url = "allpages.html"
weight = 1

[[menu.shortcuts]]
pre = "<i class='fas fa-download'></i> "
name = "Download CSV 2"
url = 'chapter-02-markdown/patches/example.csv?download=true'
weight = 2

[[menu.shortcuts]]
pre = "<i class='fas fa-link'></i> "
name = "FortiEDR Documentation"
url = 'https://docs.fortinet.com/product/fortiedr/7.0'
weight = 3

[[menu.shortcuts]]
pre = "<i class='fas fa-link'></i> "
name = "FAZ Documentation"
url = 'https://docs.fortinet.com/document/fortianalyzer/7.6.4/administration-guide/366418/setting-up-fortianalyzer'
weight = 4

[[menu.shortcuts]]
pre = "<i class='fas fa-globe'></i> "
name = "MITRE ATT&CK"
url = 'https://docs.fortinet.com/product/fortiedr/7.0'
weight = 5

[outputs]
home = ["HTML", "RSS"]

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
hrefTargetBlank = true
[markup.highlight]
guessSyntax = true
